### ISSUE TITLE
some functions or packages may be not include in the program

### ISSUE THREAD

**Issue by Summersyz** [JiaxiangYi96/mfpml#15]
Dear authhor, when i run the mf_bayesian_optimization.ipynb, some error occured as follow
Cell In[3], line 9
      6 from mfpml.models.scale_kriging import ScaledKriging
      7 from mfpml.optimization.mf_acqusitions import (AugmentedEI, ExtendedPI, VFEI,
      8                                                 VFLCB)
----> 9 from mfpml.optimization.mfbo import mfBayesOpt
     10 from mfpml.problems.multifidelity_functions import Forrester_1a, mf_Hartman3

ModuleNotFoundError: No module named 'mfpml.optimization.mfbo'

**Comment by JiaxiangYi96** [comment]
Hello, I just updated the recent version, the notebook for multi-fidelity optimization is out dated, you can refer to the online documentation for case that used for this case https://jiaxiangyi96.github.io/mfpml/optimization.html#multi-fidelity-bayesian-optimization

**Comment by Summersyz** [comment]
> Hello, I just updated the recent version, the notebook for multi-fidelity optimization is out dated, you can refer to the online documentation for case that used for this case https://jiaxiangyi96.github.io/mfpml/optimization.html#multi-fidelity-bayesian-optimization

ok，Thank you very much for open-sourcing and I salute you.
